name: .NET

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

  pull_request:
    branches: [ "main"]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ShipGame

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --collect:"XPlat Code Coverage;Format=opencover" --verbosity normal
    - name: Find coverage file
      run: find Tests/TestResults -name "*.xml" -exec mv {} Tests/TestResults/coverage.opencover.xml \;
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: Tests/TestResults/coverage.opencover.xml
        